### ISSUE TITLE
urllib2.HTTPError: HTTP Error 409: Conflict

### ISSUE THREAD

**Issue by perfekted** [akampjes/trakt-list-import#3]
I was wondering if this script is going to be updated, I can't seem to find out how to fix my error.

Thanks

**Comment by akampjes** [comment]
Hey @perfekted, do you have any steps to reproduce the error?

**Comment by perfekted** [comment]
nope no steps that I've changed,

all I did was enter this in my terminal 

python trakt-list-import.py MoviesListTest.txt (note: it only has the plain text of the movie titles)

then it processes til the end and I get this

{"imdb_id": "tt0783233"}, {"imdb_id": "tt0470679"}, {"imdb_id": "tt1971325"}, {"imdb_id": "tt0848228"}, {"imdb_id": "tt2164490"}, {"imdb_id": "tt2395427"}, {"imdb_id": "tt0085183"}], "password": "56da74df713bf416dbb19e713b4cf165a1e34471"}
Traceback (most recent call last):
  File "trakt-list-import.py", line 187, in <module>
    send_data(imdb_id_list)
  File "trakt-list-import.py", line 70, in send_data
    f = urllib2.urlopen(req)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Applications/MAMP/Library/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 409: Conflict

**Comment by akampjes** [comment]
It looks like I need to upgrade to deal with the API version 2.
Will post back here when I'm done (hopefully sometimet this week).

**Comment by perfekted** [comment]
that'll be great, I've been looking for something like this... I've been a DVDpedia user for awhile and I'm not gonna manually add all the movies I've watched... That would be crazy

Thanks Again So Much! Hear from you soon!

**Comment by akampjes** [comment]
Hey @perfekted it looks like the version 2 API requires me switching to OAuth2 authentication. That's not something that I'm going to have time to do in the near future. I would be love to review and accept a pull request if you got it working with the new API :smile: 

http://docs.trakt.apiary.io/

**Comment by perfekted** [comment]
k, no worries... Well I wanna learn to code in python so I guess this will be a project for me Thanks Again
